correcting errors flake 8
erased mentioned imports
Run flake8 .
./app/vhv_bp.py:14:1: F401 'sqlite3' imported but unused
./app/vhv_bp.py:15:1: F401 'datetime.datetime' imported but unused
./app/vhv_calculator.py:17:1: F401 'json' imported but unused
./app/vhv_calculator.py:18:1: F401 'math' imported but unused
./app/vhv_calculator.py:19:1: F401 'typing.Tuple' imported but unused
Error: Process completed with exit code 1.